# Site/SEO settings
email: noreply@example.com
baseurl: ""
permalink: /:title/
google_analytics: 

name: Olga Panasenco
title: Advanced Heliophysics
description: >
  Advanced Heliophysics is a scientific and educational organization.
  
  The organization's research will focus on studying and predicting phenomena on the Sun, and how these phenomena
  affect military and commercial hardware on Earth and near-Earth orbit. 
url: http://advancedheliophysics.com/
default_img: /assets/images/seo.jpg

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/6Q8qG-pWyt6

# Author settings
author:
  - name: Olga Panasenco
    bio: Dr. Panasenco has graduated from Moscow State University with a PhD in physics and chemistry of plasma. She has published 27 papers on solar physics in refereed scientific journals. Her research expertise includes the formation, stability and eruption of magnetic structures anchored in the photosphere (such as filaments and prominences) and the subsequent coronal mass ejections, study of solar supergranular cells and photospheric magnetic vortices at the intersections of these cells, properties of coronal pseudostreamers and their solar wind counterparts with applications to coronal heating and Alfvénic turbulence in the solar wind, and many others. 

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
sass:
    sass_dir: _assets/scss
    style: compressed
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
